version: '3.8'
services:
  app:
    build: .
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:3307/bd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password --port=3307
    ports:
      - "3307:3307"
    environment:
      - POSTGRES_DATABASE=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=secret
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data: