scrape_configs:
  - job_name: grafana
    static_configs:
      - targets: ['localhost:3000']
        labels:
          instance: 'grafana'
  - job_name: node_exporter
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'node_exporter'
  - job_name: postgres_exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: prometheus
    static_configs:
      - targets: [ "localhost:9090" ]
        labels:
          instance: 'prometheus'

global:
  scrape_interval: 15s
  evaluation_interval: 15s