spring:
  application:
    name: cicd-test
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/tvksp
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

